# 如服务器安装反作弊，则在副手攻击时有概率会被反作弊误判。
# 这里可以在副手攻击前给予玩家绕过反作弊的权限，以达到不被误判的效果。
# 如服务器未安装反作弊，可填写 "NONE" 以绕过此检测。
GRANT-PERMISSIONS:
- "NONE"

# 触发副手攻击所需要的条件。
ATTACK-REQUIRE:
  # 权限条件，如果玩家没有该权限则不会触发副手攻击。
  # 填写 "NONE" 以绕过权限检测。
  PERMISSION: "NONE"
  # 副手物品的描述判断条件，当副手物品的任意行数填有以下字段时触发副手攻击。
  # 在这里无需填写任何颜色符号，填写 "NONE" 以绕过描述检测。
  LORE-KEY: "副手武器"
  # 当主手持有食物时，且饥饿度使玩家能够食用主手食物时。就会同时触发两个操作 (则副手攻击，主手食用食物)
  # 如改成 TRUE，则会优先补充饥饿度再进行副手攻击。 (优先度调整)
  FOOD-LEVEL: true

# 触发副手攻击之后的冷却设定。
ATTACK-COOLDOWN:
  # 副手物品的冷却字段，当副手物品的任意行数填有以下字段时触发 {0} 时长的冷却效果。
  # 冷却单位: 秒。
  LORE-KEY: "副手冷却: {0}/s"
  # 是否在 ACTIONBAR 上显示冷却。
  ACTIONBAR-DISPLAY: true
  # 是否在 副手显示栏 上显示冷却。
  OFFHAND-BAR-DISPLAY: false
  # 在冷却时段尝试使用副手攻击时，是否给玩家发送信息。
  CHAT-BAR-DISPLAY: true
